version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid

  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442-4443:4442-4443"
    networks:
      - selenium-grid
    environment:
      - SE_NODE_MAX_SESSION=5
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_HUB_HOST=selenium-hub
      - SE_NODE_HUB_PORT=4444

  selenium-node-chrome:
    image: selenium/node-chrome:4.13.0
    container_name: selenium-node-chrome
    ports:
      - "5555:5555"
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid
    environment:
      - SE_NODE_HUB_HOST=selenium-hub
      - SE_NODE_HUB_PORT=4444
      - SE_NODE_MAX_SESSION=5
      - SE_NODE_SESSION_TIMEOUT=300
      - CHROME_DRIVER_EXTRA_FLAGS=--no-sandbox,--headless,--disable-dev-shm-usage

networks:
  selenium-grid:
    driver: bridge
