version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.13.0
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID=true
    networks:
      - selenium-grid

  selenium-node-chrome:
    image: selenium/node-chrome:4.13.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"  # Expose VNC port (optional)
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
